channels:
  - conda-forge
dependencies:
  - python==3.10
  - jupyterlab
  - ipywidgets
  - ipykernel
  - jupyterlab-git
  - jupyter
  - diptest
  - pillow
  - scipy
  - ffmpeg
  - rclone
  - awscli
  - hdf5tools
  - pytables
  - pip
