channels:
  - conda-forge
dependencies:
  - python==3.10
  - jupyterlab
  - ipywidgets
  - ipykernel
  - jupyterlab-git
  - jupyter
  - matplotlib
  - diptest
  - pillow
  - scipy
  - sphinx
  - sphinx-autodoc-typehints
  - sphinx_rtd_theme
  - sphinx-copybutton
  - myst-parser
  - furo
  - ffmpeg
  - rclone
  - awscli
  - hdf5tools
  - pytables
  - pytest
  - pip
