# Any commit to master branch re-builds images, re-runs tests, and pushes SHA tags to DockerHub
name: Build
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_ORG: ${{ github.repository_owner}}
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
    build-images:
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          IMAGE: [classroom]
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      # https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
      - name: Free up disk space
        run: |
          df -h
          docker image ls
          sudo apt clean
          sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc
          df -h

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{env.DOCKER_ORG}}/${{ matrix.IMAGE }}
          tags: |
            type=schedule,pattern=latest
            type=schedule,pattern={{date 'YYYY.MM.DD'}}

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.IMAGE }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
      
      - name: Inspect Image
        run: |
            docker run ${{ env.REGISTRY }}/${{env.DOCKER_ORG}}/${{ matrix.IMAGE }}:latest conda list
            docker images ls
      
      - name: Test Image
        run: |
            docker run -u 1000 -w /srv/test -v $PWD:/srv/test ${{ env.REGISTRY }}/${{env.DOCKER_ORG}}/${{ matrix.IMAGE }}:latest
